version: '3.8'
services:
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app/
            - /usr/src/app/node_modules

    postgres:
        image: postgres:14.1-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB:       ${POSTGRES_DB}
            POSTGRES_USER:     ${POSTGRES_USR}
            POSTGRES_PASSWORD: ${POSTGRES_PWD}
        volumes:
            - ./db/000-db.sql:/docker-entrypoint-initdb.d/000-db.sql
            - pg_data:/var/lib/postgresql/data

    pgadmin-compose:
        image: dpage/pgadmin4
        ports:
            - "16543:80"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        logging:
            driver: none
volumes:
    pg_data:
    pgadmin_data:
