openapi: 3.0.0
info:
  title: My API12345
  description: API documentation for My API123
  version: 1.0.0
paths:
  /posts:
    $ref: 'posts.yaml'
  /posts/{postId}:
    $ref: 'posts-postId.yaml'
  /users:
    get: 'test'
  /locations:
components:
  schemas: 
  responses:
